/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/launch`; params?: Router.UnknownInputParams; } | { pathname: `/WorkoutBuilder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/availability`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preview`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/workout/start`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/launch`; params?: Router.UnknownOutputParams; } | { pathname: `/WorkoutBuilder`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/availability`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/start`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/launch${`?${string}` | `#${string}` | ''}` | `/WorkoutBuilder${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home/profile${`?${string}` | `#${string}` | ''}` | `/onboarding/availability${`?${string}` | `#${string}` | ''}` | `/onboarding/experience${`?${string}` | `#${string}` | ''}` | `/onboarding/goal${`?${string}` | `#${string}` | ''}` | `/onboarding/preview${`?${string}` | `#${string}` | ''}` | `/onboarding/ready${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | `/workout/start${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/launch`; params?: Router.UnknownInputParams; } | { pathname: `/WorkoutBuilder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/availability`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preview`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/workout/start`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
